<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="/">
    <html>
      <head>
	       <title>Generated by blastxml_parser</title>
      </head>
      <body>
	       <xsl:apply-templates/>
      </body>
    </html>
  </xsl:template>

<!--
table containing formatted data generated here using template match instruction
!-->

  <xsl:template match="BlastOutput">
    <table width="100%" border="2">
      <tr bgcolor="silver">
	       <td>Hit number</td>
	       <td>ID</td>
	       <td>Definition</td>
	       <td>Accession</td>
      </tr>
      <xsl:for-each select="BlastOutput_iterations/Iteration/Iteration_hits/Hit">
      <!-- 'for-each' instruction used to iterate through records / nodes -
      can achieve the same thing using 'template match' instructions-->
	    <tr>
	       <td><xsl:value-of select="Hit_num"/></td>
	       <td><xsl:value-of select="Hit_id"/></td>
	       <td><xsl:value-of select="Hit_def"/></td>
	       <td><xsl:value-of select="Hit_accession"/></td>
	       <td><xsl:value-of select="Iteration_query-def"/></td>
	    </tr>
      </xsl:for-each>
    </table>
  </xsl:template>

</xsl:stylesheet>
